name: Deploy to Server

on:
  push:
    branches:
      - main  # Ejecuta la acción cuando se haga push a la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clona el repositorio para usarlo en las acciones

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H server315 >> ~/.ssh/known_hosts

    - name: Pull latest changes on server
      run: ssh derlzqbj@server315 "cd /home/derlzqbj/public_html && git pull origin main"
