name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ftp.derlacstore.com >> ~/.ssh/known_hosts

    - name: Pull latest changes on server
      run: ssh derlzqbj@ftp.derlacstore.com "cd /home/derlzqbj/public_html && git pull origin main"
