name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 21098 192.64.118.31 >> ~/.ssh/known_hosts
      - name: Test SSH
        run: ssh -p 21098 -i ~/.ssh/id_rsa derlzqbj@192.64.118.31 "echo 'Connection successful'"
