name: Deploy to Web Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host derlacstore.com\n\tStrictHostKeyChecking no\n\tPort 21098\n" > ~/.ssh/config
          ssh-keyscan -p 21098 derlacstore.com >> ~/.ssh/known_hosts

      # Paso 3: Subir los archivos al servidor
      - name: Deploy to Web Server
        run: scp -P 21098 -r ./ derlzqbj@derlacstore.com:/home/derlzqbj/public_html
