name: Deploy to Web Hosting

on:
  push:
    branches:
      - main  # El flujo se ejecutará en cada push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *\n\tStrictHostKeyChecking no\n\tPort 21098\n" > ~/.ssh/config

      # Paso 3: Subir los archivos al servidor usando SCP
      - name: Deploy to Web Server
        run: scp -P 21098 -r ./ derlzqbj@192.64.118.31:/home/derlzqbj/public_html
