name: Deploy to Server

# Cu치ndo ejecutarse
on:
  push:
    branches:
      - main  # Se ejecutar치 al hacer push en la rama main

# Configuraci칩n del trabajo
jobs:
  deploy:
    runs-on: ubuntu-latest  # Entorno donde se ejecutar치 el workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Descarga el repositorio en el entorno de GitHub Actions

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no derlzqbj@server315 "
        cd /home/derlzqbj/public_html &&
        git pull origin main"
