name: Deploy to Server

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push a la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p $HOME/.ssh  # Crear el directorio de claves SSH
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H ftp.derlacstore.com >> $HOME/.ssh/known_hosts

    - name: Pull latest changes on server
      run: ssh derlzqbj@ftp.derlacstore.com "cd /home/derlzqbj/public_html && git pull origin main"
